version: '3.8'
services:
  nest:
    image: kl4532/black-jack:nest
#    container_name: nest
#    build: black-jack-api # specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
#    container_name: mongo
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db
  frontend:
    image: kl4532/black-jack:front
#    container_name: front
#    build: black-jack
    ports:
      - "80:80"
volumes:
  data-volume:
